const huppermageIconIds: Record<string, string> = {
  "flux-denergie": "webp",
  "disque-luminescent": "webp",
  resonance: "webp",
  "lueur-de-laube": "webp",
  "rayon-crepusculaire": "webp",
  averse: "webp",
  debacle: "webp",
  "fleche-de-lumiere": "webp",
  vestige: "webp",
  "larmes-scintillantes": "webp",
  eboulement: "webp",
  faille: "webp",
  "faisceau-de-lune": "webp",
  feuillure: "webp",
  "epee-de-lumiere": "webp",
  "papillons-diurnes": "webp",
  "ombres-dansantes": "webp",
  "orbes-luisants": "webp",
  mirage: "webp",
  "halo-chatoyant": "webp",
  "forteresse-solaire": "webp",
  "surcharge-runique": "webp",
  "mur-energie": "webp",
  "visio-imperium": "webp",
  "principio-valere": "webp",
  runification: "webp",
  "coeur-de-lumiere": "png",
  "cycle-elementaire": "png",
  "feu-follet": "png",
  evasion: "webp",
  dynamo: "webp",
  antithese: "webp",
  interception: "webp",
  "distension-elementaire": "webp",
  "liaison-lumineuse": "webp",
  inspiration: "webp",
  plenitude: "webp",
  universalite: "webp",
  motivation: "webp",
  "extension-des-sens": "webp",
  "profusion-runique": "webp",
  "absorption-quadramentale": "webp",
  "refraction-elementaire": "webp",
  medecine: "webp",
  "altruisme-de-lame": "webp",
  "nouveau-souffle": "webp",
  rock: "webp",
  "essor-de-lame": "webp",
  pulsation: "webp",
  "sauvegarde-runique": "webp",
  fluctuation: "webp",
  "initiative-de-lame": "webp",
  "combinaison-elementaire": "webp",
  "transcendance-runique": "webp",
  carnage: "webp",
};

export function getHuppermageIconSrc(entryId: string): string | undefined {
  const extension = huppermageIconIds[entryId];
  return extension ? `/assets/spells/huppermage/${entryId}.${extension}` : undefined;
}
